services:
  db:
    image: mysql:8.0.40-debian
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    ports:
      - 8080:8080

  backendserver:
    image: alexandregoodmann/contabilidade-api
    container_name: contabilidade-api
    links:
      - "db"
    build: ./contabilidade-api/
    ports:
      - 8081:8081
    depends_on:
      - "db"
    restart: always
