name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile and Test
      run: mvn clean install -DskipTests=true
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3   
    - name: Build Docker Container
      run: docker run -d -p 8081:8081 --name contabilidade-api      
